# Copyright (c) 2021 Blacknon. All rights reserved.
# Use of this source code is governed by an MIT license
# that can be found in the LICENSE file.
# reference:
#   - https://motemen.hatenablog.com/entry/2019/11/github-actions-crossbuild-rust
#     - https://github.com/motemen/lssh/blob/97d3745dcc8931a1d75217573d5ca60705be632f/.github/workflows/release.yml
#   - https://github.com/greymd/teip/blob/master/.github/workflows/release.yml


name: Release Job.

on:
  push:
    branches:
      - master
      - develop

jobs:
  # build rust binary
  build:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            os: ubuntu-latest
            ext: tar.gz
          - goos: linux
            goarch: amd64
            os: ubuntu-latest
            ext: rpm
          - goos: linux
            goarch: amd64
            os: ubuntu-latest
            ext: deb
          - goos: darwin
            goarch: amd64
            os: macos-latest
            ext: tar.gz
          # - goos: windows
          #   goarch: amd64
          #   os: windows-latest
          #   ext: zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Get version
        id: package_version
        shell: bash
        run: |
          VERSION="$(go run ./cmd/lssh/ --version | awk '{print $NF}')"
          echo "::set-output name=version::$VERSION"

      - name: Build binary
        run: |
          go build ./cmd/lssh
          go build ./cmd/lscp
          go build ./cmd/lsftp

      - name: Create package file
        if: ${{ (matrix.ext == 'tar.gz') || (matrix.ext == 'rpm') || (matrix.ext == 'deb') }}
        run: |
          _TAR=lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz
          mkdir -p package/bin
          mv {lssh,lscp,lsftp} package/bin
          ## mkdir -p package/man
          ## cp man/lssh.1 package/man
          cp -r completion package/
          ## sed -i is not used due to difference between macOS and Linux
          perl -i -pe s/___VERSION___/${{ steps.package_version.outputs.version }}/ ./package/.tar2package.yml
          tar czvf "$_TAR" -C "$PWD/package" completion bin man .tar2package.yml

      # use: https://github.com/greymd/tar2package
      - name: Build rpm
        id: rpm
        if: matrix.ext == 'rpm'
        run: |
          _TAR=lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz
          docker run -i "greymd/tar2rpm:1.0.1" < "$_TAR" > lssh_${{ steps.package_version.outputs.version }}_{{ matrix.goos }}_${{ matrix.goarch }}.rpm
          echo ::set-output name=sha256::$( sha256sum lssh_${{ steps.package_version.outputs.version }}_{{ matrix.goos }}_${{ matrix.goarch }}.rpm | awk '{print $1}' )

      # use: https://github.com/greymd/tar2package
      - name: Build deb
        id: deb
        if: matrix.ext == 'deb'
        run: |
          _TAR=lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz
          docker run -i "greymd/tar2deb:1.0.1" < "$_TAR" > lssh_${{ steps.package_version.outputs.version }}_{{ matrix.goos }}_${{ matrix.goarch }}.deb
          echo ::set-output name=sha256::$( sha256sum lssh_${{ steps.package_version.outputs.version }}_{{ matrix.goos }}_${{ matrix.goarch }}.deb | awk '{print $1}' )

      - name: README for rpm
        if: matrix.ext == 'rpm'
        run: |
          _TAR=lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.rpm

      - name: Upload artifact
        if: matrix.ext == 'rpm'
        uses: actions/upload-artifact@v1
        with:
          name: build-${{ matrix.goos }}_${{ matrix.goarch }}
          path: lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.rpm

      - name: README for deb
        if: matrix.ext == 'deb'
        run: |
          _TAR=lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.deb

      - name: Upload artifact
        if: matrix.ext == 'deb'
        uses: actions/upload-artifact@v1
        with:
          name: build-${{ matrix.goos }}_${{ matrix.goarch }}
          path: lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.deb

      - name: Upload artifact
        if: matrix.ext == 'tar.gz'
        uses: actions/upload-artifact@v1
        with:
          name: build-${{ matrix.goos }}_${{ matrix.goarch }}
          path: lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz

  # create package release
  create-release:
    needs:
      - build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package_version.outputs.version }}
    steps:
      - uses: actions/checkout@v1

      - id: package_version
        name: Get version.
        shell: bash
        run: |
          VERSION="$(cargo run --example version)"
          echo "::set-output name=version::$VERSION"

      - id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package_version.outputs.version }}
          release_name: Version ${{ steps.package_version.outputs.version }}
          draft: true
          prerelease: false

      - run: |
          echo '${{ steps.create-release.outputs.upload_url }}' > release_upload_url.txt

      - uses: actions/upload-artifact@v1
        with:
          name: create-release
          path: release_upload_url.txt

  upload-release:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            os: ubuntu-latest
            ext: tar.gz
          - goos: linux
            goarch: amd64
            os: ubuntu-latest
            ext: rpm
          - goos: linux
            goarch: amd64
            os: ubuntu-latest
            ext: deb
          - goos: darwin
            goarch: amd64
            os: macos-latest
            ext: tar.gz
    needs: [create-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: create-release

      - id: upload-url
        run: |
          echo "::set-output name=url::$(cat create-release/release_upload_url.txt)"

      - uses: actions/download-artifact@v1
        with:
          name: build-${{ matrix.goos }}_${{ matrix.goarch }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload-url.outputs.url }}
          asset_path: ./build-${{ matrix.goos }}_${{ matrix.goarch }}/lssh_${{ needs.create-release.outputs.version }}_{{ matrix.goos }}_${{ matrix.goarch }}_{{ matrix.ext }}
          asset_name: lssh_${{ needs.create-release.outputs.version }}_{{ matrix.goos }}_${{ matrix.goarch }}_{{ matrix.ext }}
          asset_content_type: application/octet-stream
